// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdovqatuvlpocmxjhikx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indkb3ZxYXR1dmxwb2NteGpoaWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTY0MzMsImV4cCI6MjA3MTI5MjQzM30.hEQoHMel8snzBNI4AWmCeYZvhBwvagCaxnFkEHGZva0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});